version: '2'

services:
  api:
    image: api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      NODE_ENV: production 
    ports:
      - 5000:5000
    links:
      - auth
      - pay
      - user
      - product
  auth:
    image: auth:latest
    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    environment:
      NODE_ENV: production 
  pay:
    image: pay:latest
    build:
      context: .
      dockerfile: PayApi/Dockerfile
    environment:
      NODE_ENV: production 
    links:
      - auth
      - product
      - paydb
  user:
    image: user:latest
    build:
      context: .
      dockerfile: UsersApi/Dockerfile
    environment:
      NODE_ENV: production 
    links:
      - auth
      - userdb
  product:
    image: product:latest
    build:
      context: .
      dockerfile: ProductsApi/Dockerfile
    environment:
      NODE_ENV: production 
    links:
      - auth
      - productdb
      - es
  productdb:
    image: mongo
  userdb:
    image: mongo
  paydb:
    image: mongo
  es:
    image: elasticsearch:2.4